# Le hack le plus cool de Jupyter Notebook

In [1]:
import numpy as np

In [3]:
np.array([1,2,3])

array([1, 2, 3])

## Méthode 1

In [5]:
_3

array([1, 2, 3])

## Méthode 2

In [7]:
Out[3]

array([1, 2, 3])

## Méthode 3

In [9]:
_oh[3]

array([1, 2, 3])